---
title: "Remove_x_chromosome"
output: html_document
---

# Remove all positions call as X or Y by Elena.
## Lynx lynx MACROGEN samples

Todo esto lo corro desde la cuenta de Elena! 

Elena ha hecho un script para extraer las posiciones del X y del Y del genoma. Tiene varios pasos, (completar Elena) entre ellos quitar cualquier contig del que el 30% de sus bases dieran señal del cromosoma que fuera teniendo en cuenta que los otros podían ser Ns y que en realidad preferimos filtrar de más que de menos.

Los bed con las posiciones son:

```{bash}

/home/emarmesat/Ychr_coverage/females_males_normalized_ratio.coverage.contig.filteredY.lax.percontig.Ychr-above30.bed
/home/emarmesat/Ychr_coverage/females_males_normalized_ratio.coverage.contig.filteredX.percontig.Xchr-above30.bed

```

Estos son los bed con las posiciones del X y del Y. Ahora tengo que excluirlos de los BAM que usa Bego. Para ello primero tengo que hacer el complementario ya que bedtools substract solo usa dos beds, y bedtools intersect solo te da la intersección pero no el complementario. Por tanto, lo primero que tengo que hacer es echarles un vistazo:

```{bash}

head /home/emarmesat/Ychr_coverage/females_males_normalized_ratio.coverage.contig.filteredY.lax.percontig.Ychr-above30.bed
# lp23.s00102     1       9414    lp23.s00102c001 chrY_contig_above30per
# lp23.s00468     1       1185    lp23.s00468c001 chrY_contig_above30per
# lp23.s00622     1       1709    lp23.s00622c001 chrY_contig_above30per


head /home/emarmesat/Ychr_coverage/females_males_normalized_ratio.coverage.contig.filteredX.percontig.Xchr-above30.bed

# lp23.s00004     1       3239    lp23.s00004c001 chrX_contig_above30per
# lp23.s00006     1       2056    lp23.s00006c001 chrX_contig_above30per
# lp23.s00011     1       1187    lp23.s00011c001 chrX_contig_above30per

```

Llama la atención que son one-based y eso no debería ser así para un bed, así que los transformo en 0-based. 


```{bash}

cd /home/emarmesat/Ychr_coverage/

awk -v OFS='\t' '{print ($1,$2-1,$3)}' females_males_normalized_ratio.coverage.contig.filteredY.lax.percontig.Ychr-above30.bed > females_males_normalized_ratio.coverage.contig.filteredY.lax.percontig.Ychr-above30.0based.bed

awk -v OFS='\t' '{print ($1,$2-1,$3)}' females_males_normalized_ratio.coverage.contig.filteredX.percontig.Xchr-above30.bed >  females_males_normalized_ratio.coverage.contig.filteredX.percontig.Xchr-above30.0based.bed

```


Ahora que ya lo tengo 0 based extraigo todas las posiciones del genoma excepto las X y las Y:

```{bash}

subtractBed -a /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome.bed -b /home/emarmesat/Ychr_coverage/females_males_normalized_ratio.coverage.contig.filteredY.lax.percontig.Ychr-above30.0based.bed > /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome_without_Y_chr.bed

subtractBed -a /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome.bed -b /home/emarmesat/Ychr_coverage/females_males_normalized_ratio.coverage.contig.filteredX.percontig.Xchr-above30.0based.bed > /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome_without_X_chr.bed

subtractBed -a /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome_without_Y_chr.bed -b /home/emarmesat/Ychr_coverage/females_males_normalized_ratio.coverage.contig.filteredX.percontig.Xchr-above30.0based.bed > /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome_without_Y_X_chr.bed


# Sanity check: 
# cat bed_file_all_the_genome_without_Y_X_chr.bed | grep lp23.s00102
# lp23.s00102	9414	823758

# GREAT!

```


Bego está usando los archivos de macrogen así que los quito de ahí. 

```{bash}

cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/MACROGEN_samples_25x
mkdir MACROGEN_samples_25x_without_x_y_chr

cd /home/emarmesat/grupolince/lynx_genomes_5x/BAM_files_final/MACROGEN_samples_25x/

screen -S remove_x_and_y_positions

# Remove x and y chr:

SAMPLES=($(ls *bam))

for SAMPLE in "${SAMPLES[@]}"
do
echo "---------------------------------------------------$SAMPLE---------------------------------------------------"

bedtools intersect -a $SAMPLE -b /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome_without_Y_X_chr.bed > /home/emarmesat/grupolince/lynx_genomes_5x/BAM_files_final/MACROGEN_samples_25x/MACROGEN_samples_25x_without_x_y_chr/${SAMPLE/.bam/_without_x_y_chr.bam}

done


```


## Lynx pardinus GENOME PROJECT samples

I will do it with all of them, even thought we then only plot one or two. 

```{bash}
cd /home/emarmesat/grupolince/lynx_genomes_5x/BAM_files_final/genome_project_samples_25x
mkdir genome_project_samples_25x_without_x_y_chr

cd /home/emarmesat/grupolince/lynx_genomes_5x/BAM_files_final/genome_project_samples_25x

screen -S remove_x_and_y_positions_genome_project

# Remove x and y chr:

SAMPLES=($(ls *bam))

for SAMPLE in "${SAMPLES[@]}"
do
echo "---------------------------------------------------$SAMPLE---------------------------------------------------"

bedtools intersect -a $SAMPLE -b /home/emarmesat/grupolince/reference_genomes/lynx_pardinus_genome/bed_file_all_the_genome_without_Y_X_chr.bed > /home/emarmesat/grupolince/lynx_genomes_5x/BAM_files_final/genome_project_samples_25x/genome_project_samples_25x_without_x_y_chr/${SAMPLE/.bam/_without_x_y_chr.bam}

done


```


# Create a bed file containing autosomic positions only.

We want to have a list with autosomic position so that we can filter our windows based on autosomic vs X position in the window. 

1) We are obtaining Autosomic-sites from synteny with cat genome.
2) Then we are doing an overlap with intergenic sites from notation (we will create a BED file X intergenic). 


##1) Autosomic-sites from synteny with cat genome.

```{bash}

# 12/02/2018

cd /GRUPOS/grupolince/copia_fabascal/MAPPINGS

# Elena already obtained those. The file is:

head /GRUPOS/grupolince/copia_fabascal/MAPPINGS/lynx2cat_wTiger_AUTOSOMALchr.sorted.merged.bed

# He hecho sanity checks y los archivos parece que no están bien. El de autosomico parece q también tiene posiciiones X!!!

# A partir de aquí, ojo!!! Las dos ultimas columnas son posiciones X y posiciones autosomicas y si observamos tiene el mismo número y no debía de ser así. 
lp23.s00118	100000	150000	125000	0.016682	0.010272	0.026232	0.029158	0.019715	-0.224692	-0.141638	-0.095277	-0.213636	0.029010	2211	4168	2032	2032	c_ll_cr_n006
lp23.s00118	150000	200000	175000	0.219931	0.146627	0.423066	0.218310	0.182468	-0.649917	-0.650568	-0.539209	-0.197183	-0.092123	14496	4169	11755	11755	c_ll_cr_n006
lp23.s00118	200000	250000	225000	0.061608	0.039015	0.116851	0.070147	0.054581	-0.403916	-0.356359	-0.284544	-0.177784	-0.034422	9374	4170	7493	7493	c_ll_cr_n006
lp23.s00118	250000	300000	275000	0.232351	0.139013	0.494412	0.194088	0.166551	-0.801289	-0.811923	-0.675403	-0.146411	-0.156808	12628	4171	10174	10174	c_ll_cr_n006

# Repasar!!!

grep lp23.s00118 /home/mlucena/ANGSD_analysis/intergenic_analysis/intergenic_sfs_intergenic_Xchr/Xchr.intergenic.bed
grep lp23.s00118 /GRUPOS/grupolince/Lynx_AUTOSOMALchr/AUTOSOMAL.intergenic.bed

# Efectivamente está mal. Mirar los archivos de notación, que generó Elena a ver si también están mal y si es así comprobar los originales. Si los originales están mal, tirate por la ventana!  Sospecho que el que está mal es el de autosomico que ha generado Elena pero para comprobarlo hago algunos sanity checks (sospecha confirmada más abajo):

# ¿Cuantas posiciones tengo en el archivo de Xchr?
cat lynx2cat_wTiger_Xchr.sorted.merged.bed | awk '{sum+=($3-$2)}END{print sum}' 
# 45245057

# ¿Cuantas posiciones tengo en el archivo de notación anotadas como Xchr?
 grep chrX lynx2cat_wTiger.sorted.bed | wc -l
# 45245057

# ¡Coincide!

# ¿Cuantas posiciones tengo en el archivo de AUTOSOMAL?
cat lynx2cat_wTiger_AUTOSOMALchr.sorted.merged.bed | awk '{sum+=($3-$2)}END{print sum}' 
# 1180577743

# ¿Cuantas posiciones tengo en el archivo de notación anotadas como NO Xchr (i.e. AUTOSOMAL)?
grep -v chrX lynx2cat_wTiger.sorted.bed | wc -l
# 1135332686

# ¡No coincide!

# ¿Cuantas posiciones totales en el archivo de la notación? 
wc -l lynx2cat_wTiger.sorted.bed
# 1180577743

# El archivo anotado como AUTOSOMAL está mal. 

# Genero un nuevo archivo con el Autosómico.

grep -v chrX lynx2cat_wTiger.sorted.bed | bedtools  merge  | awk  -v OFS='\t' '{print $0,"AUTOSOMAL"}' > lynx2cat_wTiger_AUTOSOMALchr.sorted.merged.corrected.bed

# En el nuevo archivo autosómico.

cat lynx2cat_wTiger_AUTOSOMALchr.sorted.merged.corrected.bed | awk '{sum+=($3-$2)}END{print sum}'
# 1135332686
# ¡Genial! ¡¡¡Coincide!!!



```

##2) Overlap with intergenic sites from notation

```{bash}

mkdir /GRUPOS/grupolince/Lynx_AUTOSOMALchr

cd /GRUPOS/grupolince/Lynx_AUTOSOMALchr

screen -S intersect_AUTOSOMAL_intergenic

INTERGENIC_FILE="/GRUPOS/grupolince/Lyp_annotation_Apr14_final/LYPA23C.intergenic.PLUS1000.bed"
AUTOSOMAL_SINTENY="/GRUPOS/grupolince/copia_fabascal/MAPPINGS/lynx2cat_wTiger_AUTOSOMALchr.sorted.merged.corrected.bed"
OUTPUT_DIR="/GRUPOS/grupolince/Lynx_AUTOSOMALchr"


bedtools intersect -a $INTERGENIC_FILE -b $AUTOSOMAL_SINTENY -sorted -g /GRUPOS/grupolince/reference_genomes/lynx_pardinus_genome/Length_scaffolds_lp23 > $OUTPUT_DIR/AUTOSOMAL.intergenic.bed


# How many positions does it have?

awk  '{sum+=($3-$2)} END{print sum;}' AUTOSOMAL.intergenic.bed

#646299594; 


# File to cut our diversity files for non-blasted bam: /GRUPOS/grupolince/Lynx_AUTOSOMALchr/AUTOSOMAL.intergenic.bed

```


