


# Creating intergenic bam files

Yo había lanzado este script para todas las muestras de lynx lynx. Pero como tenemos varias coberturas distintas, me llevo las de MACROGEN a una subcarpeta que indiquen que tienen mas cobertura. Despues lanzo este primer script para las de lynx pardinus (5x + 25 submuestreadas a 5x), también lo lanzo para las submuestreadas de lynx lynx, y por último para las NO submuestreadas de proyecto genomas (para ponerlo en la carpeta junto a macrogen, porque para ciertos análisis necesitas tener más cobertura).

1. Para muestras 5x o muestras submuestreadas.
2. Para muestras 25x (cambia solo la ruta de las carpetas).
3. Muestras cortadas para intergénico las vuelvo a cortar con el intergénico de captura. 

# 1. Para muestras 5x.
```{bash}

# mkdir /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic
cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic

screen -S extracting_intergenic_from_bam_files_using_bedtools
script extracting_intergenic_from_bam_files_using_bedtools.log

INPUTFILE_BED="/GRUPOS/grupolince/Lyp_annotation_Apr14_final/LYPA23C.intergenic.PLUS1000.bed"
OUTPUT_DIR="/home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic"

cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/

# POPS=("c_ll_ka" "c_ll_og"  "c_ll_tu")  
# POPS=("c_lp_do" "c_lp_sm")
# POPS=("c_ll_ur")


task(){
   bedtools intersect -a $i -b /GRUPOS/grupolince/Lyp_annotation_Apr14_final/LYPA23C.intergenic.PLUS1000.bed -sorted -g /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/lp23.version.sorted.genome > $OUTPUT_DIR/${i/_recal_round-1.bam/_intergenic.bam}; # Si quiero puedo cambiar el nombre a intergenic.bam que es el final. 
   touch $OUTPUT_DIR/${i/_recal_round-1.bam/.finished}
}


for POP in ${POPS[@]}
do
echo $POP
declare -a ARRAY=($(ls "$POP"*_recal_round-1.bam)) 
for i in ${ARRAY[@]} 
do
echo $i
 task "$i" 
done
done



# Estas son las que ahora están submuestreadas y por tanto voy a repetir. 
ARRAY=("c_ll_cr_0212_recal_round-1.bam" "c_ll_ki_0090_recal_round-1.bam" "c_ll_ya_0146_recal_round-1.bam" "c_ll_vl_0112_recal_round-1.bam" "c_lr_zz_0001_recal_round-1.bam" "c_lc_zz_0001_recal_round-1.bam")

ARRAY=("c_ll_ur_0194_recal_round-1.bam" "c_ll_ur_0195_recal_round-1.bam" "c_ll_ur_0196_recal_round-1.bam" "c_ll_ur_0199_recal_round-1.bam" "c_ll_ur_0200_recal_round-1.bam")

i="c_ll_ur_0203_recal_round-1.bam"



for i in ${ARRAY[@]} 
do
echo $i
 task "$i" 
done



# Para los nuevos remapeados, los muevo a su nombre original:

for sample in $(ls *bed*)
do
echo $sample"--->"${sample/_intergenic_bed.bam/_intergenic.bam} 
mv $sample ${sample/_intergenic_bed.bam/_intergenic.bam}
done
rm *finished



for sample in $(ls *_intergenic.bam)
do
echo $sample
samtools index $sample
done


```

Tambien se podría hacer con de la siguiente manera pero es mucho más lento. 

```{bash}

cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final
for i in $( ls c_ll_og*.bam )
do
echo $i
samtools view -bH -@ 40 $i > $OUTPUT_DIR/${i/_recal_round-1/_intergenic}
while read -r -a myArray; do 
samtools view -b -@ 40 $i ${myArray[0]}:${myArray[1]}-${myArray[2]} >> $OUTPUT_DIR/${i/_recal_round-1/_intergenic}
done < $INPUTFILE_BED
done


```


# 2. Para muestras 25x del proyecto genoma (cambia solo la ruta de las carpetas)


```{bash}

mkdir /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_25x

cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_25x


screen -S extracting_intergenic_from_bam_files_using_bedtools_25x
script extracting_intergenic_from_bam_files_using_bedtools_25x.log

INPUTFILE_BED="/GRUPOS/grupolince/Lyp_annotation_Apr14_final/LYPA23C.intergenic.PLUS1000.bed"
OUTPUT_DIR="/home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_25x"

cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/genome_project_samples_25x/
POPS=("c_lp_do" "c_lp_sm")

task(){
   bedtools intersect -a $i -b /GRUPOS/grupolince/Lyp_annotation_Apr14_final/LYPA23C.intergenic.PLUS1000.bed -sorted -g /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/lp23.version.sorted.genome > $OUTPUT_DIR/${i/_recal_round-1_25x/_25x_intergenic}; # Si quiero puedo cambiar el nombre a intergenic.bam que es el final. 
   touch $OUTPUT_DIR/${i/_recal_round-1.bam/.finished}
}

for POP in ${POPS[@]}
do
echo $POP
declare -a ARRAY=($(ls "$POP"*.bam)) 
for i in ${ARRAY[@]} 
do
echo $i
 task "$i" 
done
done

```



# 3. Hago el interset de mis archivos de intergénico con los archivos intergénicos de Elena de su captura, para ser capaz de hacer blast sobre estos y tener una medida de diversidad. 

Vamos a cortar nuestros archivos intergénicos para conseguir el intergénico de Elena. Lo hacemos sobre los de intergénico por si hay alguna región que ella clasifico como intergénico que ahora no es con la nueva notación. Así que tenemos que aplicar el bed file para cortar nuestro .intergenic.bam. 

Sobre estos archivos cortados voy a hacer BLAST y despues calcular los estadísticos básicos (diversidad y FST) para ver si se corrige la contaminación de balcanes. 


```{bash}

mkdir /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_capture
cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_capture

scp home/mlucena/ANGSD_analysis/depth_calculus/no_genes_Lypa_10000longest_center_final_slop20_dot.rf /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_capture/


screen -S extracting_intergenic_capture_from_bam_files_using_bedtools
script extracting_intergenic_capture_from_bam_files_using_bedtools.log

# We convert the rf file into bed:

sed -i 's/-/ /g' no_genes_Lypa_10000longest_center_final_slop20_dot.rf 
sed -i 's/:/ /g' no_genes_Lypa_10000longest_center_final_slop20_dot.rf 


# If you are using a newer version of sed you can use -i to read from and write to the same file. Using -i you can specify a file extension so a backup will be made, incase something went wrong. Also you don't need to use the -e flag unless you are using multiple commands

mv no_genes_Lypa_10000longest_center_final_slop20_dot.rf  no_genes_Lypa_10000longest_center_final_slop20_dot.bed
sed 's/ /CTR+V+TAB/g' no_genes_Lypa_10000longest_center_final_slop20_dot.bed > no_genes_Lypa_10000longest_center_final_slop20_dot1.bed

mv no_genes_Lypa_10000longest_center_final_slop20_dot1.bed no_genes_Lypa_10000longest_center_final_slop20_dot.bed

INPUTFILE_BED="/home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_capture/no_genes_Lypa_10000longest_center_final_slop20_dot.bed"
OUTPUT_DIR="/home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_capture"

cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic

INDS=($(ls *intergenic.bam | sort | uniq))

cd /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/BAM_intergenic_capture/

task(){
   bedtools intersect -a /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/$i -b $INPUTFILE_BED -sorted -g /home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/lp23.version.sorted.genome > $OUTPUT_DIR/${i/_intergenic.bam/_intergenic_capture.bam}; # Si quiero puedo cambiar el nombre a intergenic.bam que es el final. 
   touch $OUTPUT_DIR/${i/_intergenic.bam/.finished}
}


for i in ${INDS[@]}
do
echo $i
 task "$i" 
done

# Despues me lo llevo al servidor A para hacer blast en este servidor. 


scp mlucena@genomics-b.ebd.csic.es://home/mlucena/grupolince/lynx_genomes_5x/BAM_files_final/BAM_intergenic/*_intergenic_capture.bam /home/mlucena/remove_contamination_from_lynx_lynx/ 

```
